CREATE TABLE IF NOT EXISTS employees (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  department VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL DEFAULT '',
  clearance_level INTEGER NOT NULL DEFAULT 1,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS documents (
  id SERIAL PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  source VARCHAR(255) DEFAULT 'upload' NOT NULL,
  required_clearance INTEGER NOT NULL DEFAULT 1,
  category VARCHAR(100) NOT NULL DEFAULT 'general',
  department VARCHAR(255),
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mentorship_interactions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES employees(id),
  query TEXT NOT NULL,
  intent VARCHAR(80) NOT NULL,
  hint_level INTEGER NOT NULL DEFAULT 1,
  topic VARCHAR(80) NOT NULL DEFAULT 'general',
  attempted BOOLEAN NOT NULL DEFAULT FALSE,
  compliance_issue BOOLEAN NOT NULL DEFAULT FALSE,
  sources TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skill_progress (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES employees(id),
  skill VARCHAR(80) NOT NULL,
  score DOUBLE PRECISION NOT NULL DEFAULT 50,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
